# Insert and Delete Function

In [1]:
import numpy as np

var = np.array([1, 2, 3, 4])
print(var)

y = np.insert(var , 2 , 45)
print(y)

[1 2 3 4]
[ 1  2 45  3  4]


In [9]:
# This function does not insert float number it will convert float to integer number
var1 = np.array([1, 2, 3, 4, 5, 6])
print(var1)

z = np.insert(var , (2,4) , 9.5)
print(z)
print()
# in output u can see 9.5 is converted in 9

# Using append() function
c = np.append(var1, 6.5)
print(c)
# You can add float number using append but drawback is that it only adds at the end

[1 2 3 4 5 6]
[1 2 9 3 4 9]

[1.  2.  3.  4.  5.  6.  6.5]


In [11]:
# To do this in 2D array u have to pass axis 
var1 = np.array([[1, 2, 3],[1, 2, 3]])
print(var1)
print()

# Along 0 axis 
a = np.insert(var1 , 2 , 6 , axis = 0 )
print(a)
print()

# Along 1 axis 
b = np.insert(var1 , 2 , 6 , axis = 1 )
print(b)
print()

# Using append function
d = np.append(var1 , [[23, 24, 23]], axis = 0)
print(d)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]

[[ 1  2  3]
 [ 1  2  3]
 [23 24 23]]


# Delete

In [12]:
var5 = np.array([1, 2, 3, 4])
print(var)
print()
                    # index
m = np.delete(var , 2  )
print(m)

[1 2 3 4]

[1 2 4]
