# Matrix in numpy arrays

In [1]:
# Creating a numpy matrix 
import numpy as np 

var1 = np.matrix([[1, 2, 3],[1, 2, 3]])
print(var1)
print(type(var1))
print()

# let's see deifference between them
var2 = np.array([[1, 2, 3],[1, 2, 3]])
print(var2)
print(type(var2))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [6]:
# There is nodifference in addition and multiplication function 
# matrix addition 
var3 = np.matrix([[1, 2, 3],[1, 2, 3]])
var4 = np.matrix([[1, 2, 3],[1, 2, 3]])
print(var3+var4)
print()

# array addition 
var5 = np.array([[1, 2, 3],[1, 2, 3]])
var6 = np.array([[1, 2, 3],[1, 2, 3]])
print(var5+var6)

[[2 4 6]
 [2 4 6]]

[[2 4 6]
 [2 4 6]]


In [9]:
# Let's see difference between matrix and array multiplication 
# array multiplication 
var7 = np.array([[1, 2],[1, 2]])
var8 = np.array([[1, 2],[1, 2]])
print(var7*var8)
print()

# matrix multiplication  
var9 = np.matrix([[1, 2],[1, 2]])
var10 = np.matrix([[1, 2],[1, 2]])
print(var9*var10)

[[1 4]
 [1 4]]

[[3 6]
 [3 6]]


In [10]:
# Two types to perform matrix multiplication 
var11 = np.matrix([[1, 2],[1, 2]])
var12 = np.matrix([[1, 2],[1, 2]])
print(var11*var12)
print()

x = var11.dot(var12)
print(x)

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


# Matrix function in nmupy arrays

In [5]:
import numpy as np
vr = np.matrix([[1, 2, 3],[4, 5, 6]])
print(vr)
print()

# There are two ways to perform this operation
# 1st way
x = np.transpose(vr)
print(x)
print()

# 2nd way
y = vr.T
print(y)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np
vr1 = np.matrix([[1, 2, 3],[4, 5, 6]])
print(vr1)
print()

# syntax variable_name, current_axes, converted_axes 
z = np.swapaxes(vr1, 0, 1)
print(z)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]



In [5]:
vr2 = np.matrix([[1, 2],[3, 4]])
print(vr2)
print()

a = np.swapaxes(vr2, 0, 1)
print(a)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [8]:
vr3 = np.matrix([[1, 2],[3, 4]])
print(vr3)
print()

b = np.linalg.inv(vr3)
print(b)

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
vr4 = np.matrix([[1, 2],[3, 4]])
print(vr4)
print()

# power > 0
d = np.linalg.matrix_power(vr4, 2)
print(d)
print()

# power = 0
e = np.linalg.matrix_power(vr4, 0)
print(e)
print()

# power < 0
f = np.linalg.matrix_power(vr4, -2)
print(f)

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [15]:
vr5 = np.matrix([[1, 2],[3, 4]])
print(vr5)
print()

g = np.linalg.det(vr5)
print(g)
print()

# If 2 rows are same then determinant is zero
vr6 = np.matrix([[1, 2, 3],[4, 5, 6],[1, 2, 3]])
h = np.linalg.det(vr6)
print(h)

[[1 2]
 [3 4]]

-2.0000000000000004

0.0
