## Create numpy arrays with random number

**1) rand()** -- This function is used to generate random value between 0 to 1 [0,1) <br>

**2) randn()** -- This function used to generate number closer to 0 number can be positive or negative <br>

**3) ranf()** -- This function used to generate numbers between interval [0.0 ,1.0) there is round bracket at end in interval that means 1 is not includede <br>

**4) randint()** -- This function is used to generate number between given range

In [5]:
# rand()

import numpy as np

var = np.random.rand(4)
var0 = np.random.rand(4, 3)

print(var)
print()
print(var0)

[0.93517969 0.99200687 0.08415378 0.64630861]

[[0.06908867 0.64477836 0.38403554]
 [0.43855712 0.97287669 0.89550535]
 [0.24188951 0.49476367 0.60826122]
 [0.99951958 0.35528335 0.27319059]]


In [7]:
# randn()

var1 = np.random.randn(4)
var2 = np.random.randn(4, 3)

print(var1)
print()
print(var2)


[-0.89727348 -0.10733989 -0.02643915  0.15166607]

[[-1.98399685 -1.36585789 -0.89481527]
 [ 2.08916169 -0.79459472  0.09717054]
 [-2.33159555 -1.10282482 -1.39129726]
 [-0.22734334 -1.47526228 -0.4061286 ]]


In [9]:
# ranf()

var3 = np.random.ranf(4)
# var4 = np.random.ranf(4, 3)
# this function only take 1 arguement 

print(var3)
print()



[0.17429536 0.20423401 0.57043229 0.30025346]



In [12]:
# randint()
# var = np.random.randint(min, max, total_values)

var5 = np.random.randint(1,10,5)
var6 = np.random.randint(10,30,10)

print(var5)
print(var6)


[5 2 3 5 4]
[18 15 14 13 22 27 26 26 24 10]
