## Shape and reshaping of arrays in numpy

In [2]:
import numpy as np
var = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(var)
print()
print(var.shape)

# o/p (2, 4) 2 -- rows  4 -- column

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [3]:
var_1 = np.array([1, 2, 3, 4], ndmin = 4 )
print(var_1)
print()
print(var_1.shape)

# o/p -- (1, 1, 1, 4)
# there only 1 row and 4 columns

[[[[1 2 3 4]]]]

(1, 1, 1, 4)


## Reshaping

In [4]:
var_2 = np.array([1, 2, 5, 6, 7, 8])
print(var_2)
print(var_2.ndim)
print()

x = var_2.reshape(2,3)
print(x)
print(x.ndim)

[1 2 5 6 7 8]
1

[[1 2 5]
 [6 7 8]]
2


In [15]:
# 3D array
var_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(var_3)
print(var_3.ndim)
print()

# 1D array converted in 3D array
x = var_3.reshape(2,3,2)
print(x)
print(x.ndim)
print()

# Again converting 3D array in 1D array pass -1 to make 1D array
one = var_3.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
