# Iterating Numpy Arrays

In [2]:
# Iteration for 1D arrays
import numpy as np 
x = np.array([5, 9, 7, 3])
print(x)
print()
for i in x :
    print(i)

[5 9 7 3]

5
9
7
3


In [3]:
# Iteration for 2D arrays
y = np.array([[3, 4, 6, 7],[2, 9, 3, 5]])
print(y)
print()
# After this process data is iterated but still in matrix if u want data like in 1D arrays
for j in y :
    print(j)
print()
# For each data seperately
for k in y:
    for l in k:
        print(l)

[[3 4 6 7]
 [2 9 3 5]]

[3 4 6 7]
[2 9 3 5]

3
4
6
7
2
9
3
5


In [6]:
# Iteration for 3D arrays 
z = np.array([[[9, 8, 7, 6],[5, 6, 7, 3],[1, 3, 4, 2]]])
print(z)
print(z.ndim)
print()
for i in z :
    for j in i :
        for k in j :
            print(k)

[[[9 8 7 6]
  [5 6 7 3]
  [1 3 4 2]]]
3

9
8
7
6
5
6
7
3
1
3
4
2


In [7]:
g = np.array([[[9, 8, 2, 6],[6, 9, 7, 2],[1, 3, 8, 2]]])
print(g)
print(g.ndim)
print()
for i in np.nditer(g):
    print(i)

[[[9 8 2 6]
  [6 9 7 2]
  [1 3 8 2]]]
3

9
8
2
6
6
9
7
2
1
3
8
2


In [12]:
h = np.array([[[9, 3, 2, 6],[4, 9, 7, 2],[9, 3, 8, 2]]])
print(h)
print(g.ndim)
print()
for i in np.nditer(h, flags=["buffered"], op_dtypes = "S"):
    print(i)
    
# In output small b reprsent that data is stored in bufferef

[[[9 3 2 6]
  [4 9 7 2]
  [9 3 8 2]]]
3

b'9'
b'3'
b'2'
b'6'
b'4'
b'9'
b'7'
b'2'
b'9'
b'3'
b'8'
b'2'


In [14]:
f = np.array([[[9, 8, 2, 6],[6, 9, 7, 2],[1, 3, 8, 2]]])
print(f)
print(f.ndim)
print()
for i,d in np.ndenumerate(f):
    print(i,d)

[[[9 8 2 6]
  [6 9 7 2]
  [1 3 8 2]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 2
(0, 0, 3) 6
(0, 1, 0) 6
(0, 1, 1) 9
(0, 1, 2) 7
(0, 1, 3) 2
(0, 2, 0) 1
(0, 2, 1) 3
(0, 2, 2) 8
(0, 2, 3) 2
