## Lec - 3 ##
### Creating numpy arrays ###

**To create a numpy array basic syntax is**<br> 

import random as np <br>
*Here u pass a list of number which is converted into array* <br>
a = np.array([1, 2, 3]) <br>
print(a)

In [1]:
import numpy as np

x = [1, 2, 3, 4]

y = np.array(x)

print(y)

[1 2 3 4]


In [2]:
#Just entering the array variable name it will tell u whether it is array or not 
y

array([1, 2, 3, 4])

In [4]:
print(type(y))

<class 'numpy.ndarray'>


In [6]:
# How to take user input 

# Create empty list
l = [] 

# I wan't four element in ,y array so for loop will run for 4 times
for i in range(1,5):
    num = int(input("Enter the number : "))
    # Add the input number to the list 
    l.append(num)

# To print the array after converting list to array at the same time 
print(np.array(l))

Enter the number : 23
Enter the number : 34
Enter the number : 45
Enter the number : 56
[23 34 45 56]


## Dimensions in Array ##

**1) 1 Dimension Array** <br>
  [1, 2, 3, 4] <br>

**2) 2 Dimension Array** <br>
  [[1, 2, 3, 4]] <br>

**3) 3 Dimension Array** <br>
  [[[1, 2, 3, 4]]] <br>
 
To check the dimension of array count the no.of bracket at any one side <br>
                      OR <br>
ndim function is used to find out dimension of array <br>

In [8]:
# 1 Dimension Array 
a = [1, 2, 3, 4]

b = np.array(a)

print(b.ndim)

1


In [15]:
# How to create 2 Dimension Array 
x = np.array([1, 2, 3, 4])
print(x)
print(x.ndim)
print("\n")
# Other way to create is 
y = np.array([[1, 2, 3, 4],[3, 4, 6, 8]])
print(y)
print(y.ndim)

[1 2 3 4]
1


[[1 2 3 4]
 [3 4 6 8]]
2


In [16]:
# ther's one prblm in creating 2 Dimension array 
z = np.array([[1, 2, 3, 4],[3, 4, 6]])
print(z)

# Here u get an error bcuz no.of element in two rows are not equal in number 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
# 3 Dimension Array 
d = np.array([[[1, 2, 3, 4],[3, 4, 6, 7],[8, 9, 3,1]]])
print(d)
print(d.ndim)

[[[1 2 3 4]
  [3 4 6 7]
  [8 9 3 1]]]
3


In [18]:
# How to create Multidinmension array
c = np.array([1, 2, 3, 4] , ndmin = 10)
print(c)
print(c.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
