# INDEXING

In [2]:
# 1D array indexing
import numpy as np

var = np.array([1, 6, 3, 8])
#               0  1  2  3
#              -4 -3 -2 -1

print(var[3])
print(var[-2])

8
3


In [7]:
# 2D array indexing 
var1 = np.array([[3, 5, 7],[9, 1, 4]])
print(var1)
print(var1.ndim)
print()
# First placeholder to specify the row and second placeholder to specify the element of the row  
print(var1[0][1])
print(var1[1][2])

[[3 5 7]
 [9 1 4]]
2

5
4


In [10]:
# 3D array indexing

var2 = np.array([[[1, 2],[6, 7]]])
print(var2)
print(var2.ndim)
print()
# refer the diagram
#   [ [ [1, 2] -- 0          ---- 0
#       [6, 7]]] --- 1
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# SLICING

In [22]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
#             0  1  2  3  4  5  6  7
print(x)
print()
print("2 to 5 : ",x[1:5])
print()
print("Odd numbers : ",x[0:7:2])
print()
# If u want the whole data set you need not to specify the ending index 
print("Even numbers : ",x[1::2])
print()
# if u want the data set from starting alo no need to mention starting index 
print("start to 5 : ",x[:5:])
print()
# to print whole data set at a step size of 3
print("step size of 3: ",x[::3])

[1 2 3 4 5 6 7 8]

2 to 5 :  [2 3 4 5]

Odd numbers :  [1 3 5 7]

Even numbers :  [2 4 6 8]

start to 5 :  [1 2 3 4 5]

step size of 3:  [1 4 7]


In [38]:
y = np.array([[1, 2, 3],[6, 7, 8],[11, 12, 13]])
# element inex 0  1  2  3   4  5  6  7    8   9  10  11  
print(y)
print(y.ndim)
print()
#7 8 12 13 :
print(y[1: , 1:])
print()
# 6 7 8
print(y[1:2,])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
2

[[ 7  8]
 [12 13]]

[[6 7 8]]
