## Special Numpy Array

In [1]:
# Array filled with ZERO's

import numpy as np

# 1D zero array
arr_zero1D = np.zeros(4)

# 2D zero array
arr_zero2D = np.zeros((3, 4))

# 3D zero array
arr_zero3D = np.zeros(((3, 4, 3)))

print(arr_zero1D)
print()
print(arr_zero2D)
print()
print(" 3D array starts ")
print(arr_zero3D)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 3D array starts 
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [2]:
# Array filled with ones
arr_ones = np.ones(4)
print(arr_ones)

# Similarly u can create for 2D and 3D array

[1. 1. 1. 1.]


In [3]:
# Empty array 
arr_em = np.empty(4)
print(arr_em)

# Here u can see 1 in your empty array bcuz when we create an empty array it takes up the value of prevois memory location

[1. 1. 1. 1.]


In [5]:
# An array with a range of element
arr_ran = np.arange(4)

arr_ran0 = np.arange(2,6)

arr_ran1 = np.arange(3,7)

print(arr_ran)
print(arr_ran0)
print(arr_ran1)

[0 1 2 3]
[2 3 4 5]
[3 4 5 6]


In [6]:
# Making all diagonal element 1
arr_dia = np.eye(3)
arr_dia0 = np.eye(4,4)

print(arr_dia)
print()
print(arr_dia0)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# Create an array with values that are spaced linearly in specified interval
# num specify no.of element should be there in array
arr_lin = np.linspace(0,10,num = 5)
arr_lin0 = np.linspace(0,20,num = 5)

print(arr_lin)
print()
print(arr_lin0)

[ 0.   2.5  5.   7.5 10. ]

[ 0.  5. 10. 15. 20.]
