## Broadcasting Numpy arrays

In [2]:
import numpy as np

# This is called Broadcast error
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3])

print( var1 + var2 )

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [4]:
# Error was there bcuz of less element in one array
var1 = np.array([1, 2, 3, 4])
var2 = np.array([1, 2, 3, 4])

print( var1 + var2 )

[2 4 6 8]


In [6]:
var1 = np.array([1, 2, 3])
print(var1.shape)
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print()

print( var1 + var2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [9]:
x = np.array([[1],[2]])
print(x.shape)
print(x)
print()

y = np.array([[1, 2, 3],[1, 2, 3]])
print(y.shape)
print(y)
print()

print( x + y )


(2, 1)
[[1]
 [2]]

(2, 3)
[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]
