# Numpy array Functions  

In [3]:
import numpy as np

var = np.array([2, 4, 5, 8, 2, 1, 9, 6, 7, 2])
# index         0  1  2  3  4  5  6  7  8  9

x = np.where( var == 2 )
print(x)
print()

# You can also perform some operation on array and use where function
y = np.where( (var % 2 ) == 0 )
print(y)
print()


(array([0, 4, 9], dtype=int64),)

(array([0, 1, 3, 4, 7, 9], dtype=int64),)



In [6]:
var_1 = np.array([1, 2, 3, 4, 6, 7, 9, 11])
# index           0  1  2  3  4  5  6 

z = np.searchsorted(var_1, 5)
print(z)
# 5 should be inserted at position at index 4 to maintain order

# If u wan't u can also pass list of number
a = np.searchsorted(var_1, [5, 8, 10])
print(a)

4
[4 6 7]


In [8]:
# Sorting of number
vr = np.array([3, 6, 34, 78, 9, 45, 21])

print(np.sort(vr))

[ 3  6  9 21 34 45 78]


In [9]:
# Sorting of alphabets 
vr1 = np.array(["c", "r", "z", "v"])

print(np.sort(vr1))

['c' 'r' 'v' 'z']


In [10]:
# Sorting of 2D array
vrr = np.array([[3, 6, 34], [78, 9, 45], [21, 56, 12]])

print(np.sort(vrr))

[[ 3  6 34]
 [ 9 45 78]
 [12 21 56]]


In [12]:
vr4 = np.array(["c", "r", "z", "v"])

f = [True, False, True, False]

new_arr = vr4[f]
print(new_arr)

['c' 'z']
