# Joining and Split of numpy arrays

In [2]:
# Merging of 1D arrays 
import numpy as np 

var1 = np.array([5, 4, 3, 2, 1])
var2 = np.array([6, 7, 8, 9, 10])

add = np.concatenate((var1, var2))
print(add)

[ 5  4  3  2  1  6  7  8  9 10]


In [9]:
# Merging in 2D arrays
vr1 = np.array([[5, 4], [3, 2]])
vr2 = np.array([[6, 7], [8, 9]])
print(vr1)
print()
print(vr2)
print()

# Merging will be done downward 
axis0 = np.concatenate((vr1, vr2), axis = 0)
print(axis0)
print()

# Merging will be done horizontally 
axis1 = np.concatenate((vr1, vr2), axis = 1)
print(axis1)

[[5 4]
 [3 2]]

[[6 7]
 [8 9]]

[[5 4]
 [3 2]
 [6 7]
 [8 9]]

[[5 4 6 7]
 [3 2 8 9]]


In [17]:
var_1 = np.array([5, 4, 3, 2, 1])
var_2 = np.array([6, 7, 8, 9, 10])

# Merging along axis 0 
a_new = np.stack((var_1, var_2), axis = 0)
print(a_new)
print()

# Merging along axis 1
a_new1 = np.stack((var_1, var_2), axis = 1)
print(a_new1)
print()

# Merging along row  
a_new2 = np.hstack((var_1, var_2))
print(a_new2)
print()

# Merging along column  
a_new3 = np.vstack((var_1, var_2))
print(a_new3)
print()

# Merging along column  
a_new4 = np.dstack((var_1, var_2))
print(a_new4)
print()

[[ 5  4  3  2  1]
 [ 6  7  8  9 10]]

[[ 5  6]
 [ 4  7]
 [ 3  8]
 [ 2  9]
 [ 1 10]]

[ 5  4  3  2  1  6  7  8  9 10]

[[ 5  4  3  2  1]
 [ 6  7  8  9 10]]

[[[ 5  6]
  [ 4  7]
  [ 3  8]
  [ 2  9]
  [ 1 10]]]



# Spliting

In [22]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print()

arr = np.array_split(x, 3)
print(arr)
print(type(arr))
print()

# To acess array from list u can use index
print(arr[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>

[1 2]


In [25]:
# Similarly u can do it for 1D array
y = np.array([[1, 2], [3, 4], [5, 6]])
print(y)
print()

ar = np.array_split(y, 3)
print(ar)
print()

# You can also split along axis
ar1 = np.array_split(y, 3, axis =1)
print(ar1)
print()

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

