## Arithmatic operation 

## 1 Dimension array

In [3]:
# Addition of one element in an array
import numpy as np

var = np.array([1, 2, 3, 4])

var_add = var + 3

print(var_add)

[4 5 6 7]


In [6]:
# Addition of two arrays
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([1, 2, 3, 4])

var_add = var_1 + var_2

print(var_add)

[2 4 6 8]


In [7]:
# Subraction 
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([1, 2, 3, 4])

var_add = var_1 - var_2

print(var_add)

[0 0 0 0]


In [8]:
# Multiplication 
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([1, 2, 3, 4])

var_add = var_1 * var_2

print(var_add)

[ 1  4  9 16]


In [9]:
# Division 
var_1 = np.array([1, 2, 3, 4])
var_2 = np.array([1, 2, 3, 4])

var_add = var_1 / var_2

print(var_add)

[1. 1. 1. 1.]


In [12]:
# Using function
var_2 = np.array([1, 2, 3, 4])
var_3 = np.array([1, 2, 3, 4])

varadd = np.add(var_2, var_3)
varadd0 = np.add(var_2, 5)

print(varadd)
print()
print(varadd0)

[2 4 6 8]

[6 7 8 9]


## 2 Dimension array

In [14]:
var_21 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
var_22 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])

print(var_21)
print()
print(var_22)
print()

var_add2 = np.add(var_21,var_22)
print(var_add2)
print()

var_multiply2 = np.multiply(var_21,var_22)
print(var_multiply2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]

[[ 1  4  9 16]
 [ 1  4  9 16]]
