# Arithmetic Function

In [2]:
import numpy as np
var_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.random.shuffle(var_1)

print(var_1)

[1 8 5 4 3 7 2 6]


In [9]:
var_2 = np.array([1, 2, 3, 2, 4, 6, 6, 7, 4, 2, 6])

x = np.unique(var_2)
print(x)
print()

# If you want the index then set return_index as True
y = np.unique(var_2, return_index = True)
print(y)
print()

# If you want the count then set return_count as True
z = np.unique(var_2, return_index = True, return_counts = True)
print(z)

[1 2 3 4 6 7]

(array([1, 2, 3, 4, 6, 7]), array([0, 1, 2, 4, 5, 7], dtype=int64))

(array([1, 2, 3, 4, 6, 7]), array([0, 1, 2, 4, 5, 7], dtype=int64), array([1, 3, 1, 2, 3, 1], dtype=int64))


In [11]:
var_3 = np.array([4, 5, 6, 1, 2, 3])

z = np.resize(var_3,(2,3))
print(z)
print()

n = np.resize(var_3,(3,2))
print(n)

[[4 5 6]
 [1 2 3]]

[[4 5]
 [6 1]
 [2 3]]


In [16]:
# Let's make a 2D array
var_4 = np.array([[4, 5], [6, 1], [2, 3]])
print(var_4)
print()

# Convert this 2D array in 1D by default it converts in column wise so no need to pass any parameter
l = var_4.flatten()
m = np.ravel(var_4)
print(l)
print()
print(m) 

[[4 5]
 [6 1]
 [2 3]]

[4 5 6 1 2 3]

[4 5 6 1 2 3]


In [21]:
# Let's use order 
var_5 = np.array([[4, 5], [6, 1], [2, 3]])
print(var_5)
print()

# 'F' means to flatten in column-major (Fortran-style) order. 
q = var_4.flatten(order = "F")
r = np.ravel(var_4,order = "F")
print("Flatten : ",q)
print("Ravel : ",r)
print()

# 'A' means to flatten in column-major order if 'a' is Fortran *contiguous* in memory,row-major order otherwise.
s = var_4.flatten(order = "A")
t = np.ravel(var_4,order = "A")
print("Flatten : ",s)
print("Ravel : ",t)
print()

# 'K' means to flatten 'a' in the order the elements occur in mem^ 
u = var_4.flatten(order = "K")
v = np.ravel(var_4,order = "K")
print("Flatten : ",u)
print("Ravel : ",v)
print()

[[4 5]
 [6 1]
 [2 3]]

Flatten :  [4 6 2 5 1 3]
Ravel :  [4 6 2 5 1 3]

Flatten :  [4 5 6 1 2 3]
Ravel :  [4 5 6 1 2 3]

Flatten :  [4 5 6 1 2 3]
Ravel :  [4 5 6 1 2 3]

