## Data types Numpy array

In [2]:
import numpy as np

var = np.array([1, 3, 5, 8, 45, 87])

print("data type : ",var.dtype)

data type :  int32


In [3]:
var = np.array([1, 3.5, 5, 8.48, 45, 87])

print("data type : ",var.dtype)

data type :  float64


In [4]:
var = np.array(["a", "D", "g"])

print("data type : ",var.dtype)

data type :  <U1


In [5]:
var = np.array([1, 3, 5, 8, 45, 87, "j", "H"])

print("data type : ",var.dtype)

data type :  <U11


In [8]:
# Conversion btwn data type 
# Conversion btwn int32 to int8
x = np.array([1, 2, 3, 4],dtype = np.int8)
print("data type : ",x.dtype)

data type :  int8


In [9]:
# Conversion from int32 to float
x1 = np.array([1, 2, 3, 4],dtype = "f")
print("data type : ",x1.dtype)

data type :  float32


In [11]:
# Another way to convert
x2 = np.array([1, 2, 3, 4]) 
new = np.float32(x2)

print("Data type : ",x2.dtype)
print("Data type : ",new.dtype)
print(x2)
print(new)

Data type :  int32
Data type :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [12]:
# Conversion from int to float then again float to int 
x2 = np.array([1, 2, 3, 4]) 
new = np.float32(x2)
new_one = np.int_(new)

print("Data type : ",x2.dtype)
print("Data type : ",new.dtype)
print("Data type : ",new_one.dtype)

print(x2)
print(new)
print(new_one)


Data type :  int32
Data type :  float32
Data type :  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [13]:
# Direct conversion from int to float using astype function 
x3 = np.array([1, 2, 3, 4])
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
