## Arithmetic operation

In [8]:
# First 4 operation
import numpy as np

var_1 = np.array([2, 3, 1, 4, 8, 6, 5, 9])

print("min : " ,np.min(var_1), "index : " ,np.argmin(var_1))
print("max : " ,np.max(var_1), "index : " ,np.argmax(var_1))

# sqrt()
print("sqrt : ",np.sqrt(var_1))

min :  1 index :  2
max :  9 index :  7
sqrt :  [1.41421356 1.73205081 1.         2.         2.82842712 2.44948974
 2.23606798 3.        ]


In [9]:
# Working with 2 Dimension array
# here we have to pass axis along with variable in functions 
# 2D arrays have two axis 0 and 1
# 0 --- rows    1 --- columns
var_1 = np.array([[2, 3, 1, 4],[8, 6, 5, 9]])
print(var_1)
print()
print(np.min(var_1,axis = 0))
print()
print(np.min(var_1, axis = 1))

[[2 3 1 4]
 [8 6 5 9]]

[2 3 1 4]

[1 5]


In [11]:
# sin and cos 
var_2 = np.array([0, 30, 45, 60, 90, 180])

print("sin value : ",np.sin(var_2))
print("cos value : ",np.cos(var_2))


sin value :  [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666 -0.80115264]
cos value :  [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362 -0.59846007]


In [13]:
# cumsum()
#      Ex. [1, 2, 3] === [1, 1+2, 1+2+3] === [1 3 3+3] === [1 3 6]           
var_3 = np.array([1, 2, 3])
print("cumsum value : ",np.cumsum(var_3))

cumsum value :  [1 3 6]
